name: "go: build dev binaries"

on:
  push:
    branches: [ master ]
permissions:
    contents: write
    packages: write

jobs:
  release-linux-amd64:
    name: release windows/amd64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: wangyoucao577/go-release-action@v1
      with:
        github_token: ${{ secrets.MY_GITHUB_TOKEN }}
        goos: windows
        goarch: amd64
        pre_command: export CGO_ENABLED=0
